### PR TITLE
Make ocaml-minisat friendly with continuous integration

### PR DESCRIPTION
**Pull request by maelvls**
Hi,

Thank you so much for this ocaml binding for minisat. I tweaked it in order to have a linux/windows/mac build that works on the project [touist](https://github.com/touist/touist).

Edits for continous integration:
- removed symlinks of src/solver.h, src/solver.c, src/vec.c
  and replaced them by the actual files; I did that because
  in cygwin, ocamlc wouldn't find solver.h in #include "solver.h".
  I might be mistaken but it's the only thing I found to avoid the
  problem...
- modified the uint64 typedef that was causing issues in cygwin+ocamlc.
  In fact, the '#ifdef _WIN32' wasn't proper for cygwin builds;
  plus, the uint64 isn't standard, changed to uint64_t.
  See the SO topic here: http://stackoverflow.com/questions/126279

### CODE REVIEW

**Comment by c-cube** [comment]
I suppose I have to give access to travis for the CI, is that right?

**Comment by maelvls** [comment]
Yep! But I didn't actually prepare a `.travis-ci.yml`, but I could do so if you want!

**Comment by c-cube** [comment]
If it doesn't bother you, I'd be thankful, yes.

**Comment by maelvls** [comment]
Done in PR #2! 😀

**Pull request merged**
